"""MusicXML 4.0 generation for piano music."""

from __future__ import annotations

import math
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

from .midi_generation import MidiAnalysis, NoteEvent

# MusicXML pitch names
PITCH_NAMES = ["C", "D", "E", "F", "G", "A", "B"]
ACCIDENTAL_NAMES = ["", "sharp", "flat", "natural", "double-sharp", "double-flat"]


def _midi_to_step_and_alter(midi_note: int) -> tuple[str, int, str]:
    """Convert MIDI note number to MusicXML step, alter, and octave."""
    octave = (midi_note // 12) - 1
    pitch_class = midi_note % 12
    
    # Pitch class to step and alter
    step_alter_map = {
        0: ("C", 0),
        1: ("C", 1),   # C# / Db
        2: ("D", 0),
        3: ("D", 1),   # D# / Eb
        4: ("E", 0),
        5: ("F", 0),
        6: ("F", 1),   # F# / Gb
        7: ("G", 0),
        8: ("G", 1),   # G# / Ab
        9: ("A", 0),
        10: ("A", 1),  # A# / Bb
        11: ("B", 0),
    }
    
    step, alter = step_alter_map[pitch_class]
    
    # Determine accidental display
    accidental = ""
    if alter == 1:
        accidental = "sharp"
    elif alter == -1:
        accidental = "flat"
    elif alter == 2:
        accidental = "double-sharp"
    elif alter == -2:
        accidental = "double-flat"
    
    return step, alter, accidental


def _duration_to_musicxml_divisions(duration: float, tempo: float, ticks_per_beat: int = 480) -> tuple[int, str]:
    """Convert duration in seconds to MusicXML duration and type."""
    # Calculate beats per second
    beats_per_second = tempo / 60.0
    beats = duration * beats_per_second
    
    # Convert to divisions (1/4 note = 1 beat, 480 divisions per beat)
    divisions = int(round(beats * ticks_per_beat))
    
    # Determine note type
    whole_note_divisions = ticks_per_beat * 4
    
    if divisions >= whole_note_divisions:
        return divisions, "whole"
    elif divisions >= whole_note_divisions // 2:
        return divisions, "half"
    elif divisions >= whole_note_divisions // 4:
        return divisions, "quarter"
    elif divisions >= whole_note_divisions // 8:
        return divisions, "eighth"
    elif divisions >= whole_note_divisions // 16:
        return divisions, "16th"
    else:
        return divisions, "32nd"


def _format_xml_element(tag: str, content: str | int | float, indent: int = 0) -> str:
    """Format a simple XML element."""
    prefix = " " * indent
    return f"{prefix}<{tag}>{content}</{tag}>\n"


def _format_xml_element_with_attr(tag: str, content: str, attrs: dict[str, str], indent: int = 0) -> str:
    """Format an XML element with attributes."""
    prefix = " " * indent
    attr_str = " ".join(f'{k}="{v}"' for k, v in attrs.items())
    return f"{prefix}<{tag} {attr_str}>{content}</{tag}>\n"


def generate_musicxml(
    melody: Iterable[NoteEvent],
    accompaniment: Iterable[NoteEvent],
    analysis: MidiAnalysis,
    title: str = "Untitled",
    include_source: bool = False,
) -> str:
    """Generate MusicXML 4.0 format string from note events.
    
    Args:
        melody: Melody note events
        accompaniment: Accompaniment note events
        analysis: MIDI analysis results
        title: Work title
        include_source: If True, include original music timing. If False, only generated music.
    """
    
    melody_list = list(melody)
    accompaniment_list = list(accompaniment)
    
    # Calculate total duration
    all_notes = melody_list + accompaniment_list
    if not all_notes:
        total_duration = 0.0
    else:
        total_duration = max(note.start + note.duration for note in all_notes)
    
    # Generate the MusicXML document
    lines: list[str] = []
    
    # XML declaration and DOCTYPE
    lines.append('<?xml version="1.0" encoding="UTF-8"?>')
    lines.append('<!DOCTYPE score-partwise PUBLIC "-//Recordare//DTD MusicXML 4.0 Partwise//EN" "http://www.musicxml.org/dtds/partwise.dtd">')
    lines.append('<score-partwise version="4.0">')
    
    # Work title
    lines.append('  <work>')
    lines.append(f'    <work-title>{_escape_xml(title)}</work-title>')
    lines.append('  </work>')
    
    # Identification
    lines.append('  <identification>')
    lines.append('    <rights>Generated by LonelyPianist</rights>')
    lines.append('    <encoding>')
    lines.append('      <software>LonelyPianist Piano Dialogue Server</software>')
    lines.append('      <encoding-date>2026-01-01</encoding-date>')
    lines.append('    </encoding>')
    lines.append('  </identification>')
    
    # Part list
    lines.append('  <part-list>')
    lines.append('    <score-part id="P1">')
    lines.append('      <part-name>Melody</part-name>')
    lines.append('    </score-part>')
    if accompaniment_list:
        lines.append('    <score-part id="P2">')
        lines.append('      <part-name>Accompaniment</part-name>')
        lines.append('    </score-part>')
    lines.append('  </part-list>')
    
    # Part 1: Melody
    lines.append('  <part id="P1">')
    lines.append('    <measure number="1">')
    
    # Measure attributes
    lines.append('      <attributes>')
    lines.append('        <divisions>480</divisions>')
    lines.append('        <key>')
    lines.append(f'          <fifths>{_key_to_fifths(analysis.key_signature)}</fifths>')
    lines.append(f'          <mode>{analysis.key_mode}</mode>')
    lines.append('        </key>')
    lines.append('        <time>')
    lines.append(f'          <beats>{analysis.time_signature[0]}</beats>')
    lines.append(f'          <beat-type>{analysis.time_signature[1]}</beat-type>')
    lines.append('        </time>')
    lines.append('        <clef>')
    lines.append('          <sign>G</sign>')
    lines.append('          <line>2</line>')
    lines.append('        </clef>')
    lines.append('      </attributes>')
    
    # Tempo
    lines.append('      <direction>')
    lines.append('        <sound>')
    lines.append(f'          < tempo>{int(analysis.tempo_bpm)}</tempo>')
    lines.append('        </sound>')
    lines.append('      </direction>')
    
    # Generate melody notes
    melody_lines = _generate_part_notes(melody_list, analysis.tempo_bpm)
    lines.extend(melody_lines)
    
    lines.append('    </measure>')
    lines.append('  </part>')
    
    # Part 2: Accompaniment (if exists)
    if accompaniment_list:
        lines.append('  <part id="P2">')
        lines.append('    <measure number="1">')
        
        # Attributes for accompaniment
        lines.append('      <attributes>')
        lines.append('        <divisions>480</divisions>')
        lines.append('        <key>')
        lines.append(f'          <fifths>{_key_to_fifths(analysis.key_signature)}</fifths>')
        lines.append(f'          <mode>{analysis.key_mode}</mode>')
        lines.append('        </key>')
        lines.append('        <time>')
        lines.append(f'          <beats>{analysis.time_signature[0]}</beats>')
        lines.append(f'          <beat-type>{analysis.time_signature[1]}</beat-type>')
        lines.append('        </time>')
        lines.append('        <clef>')
        lines.append('          <sign>F</sign>')
        lines.append('          <line>4</line>')
        lines.append('        </clef>')
        lines.append('      </attributes>')
        
        # Generate accompaniment notes
        acc_lines = _generate_part_notes(accompaniment_list, analysis.tempo_bpm)
        lines.extend(acc_lines)
        
        lines.append('    </measure>')
        lines.append('  </part>')
    
    lines.append('</score-partwise>')
    
    return "".join(lines)


def _key_to_fifths(key_signature: str) -> int:
    """Convert key name to fifths count for MusicXML."""
    key_map = {
        "C": 0, "G": 1, "D": 2, "A": 3, "E": 4, "B": 5, "F#": 6, "C#": 7,
        "F": -1, "Bb": -2, "Eb": -3, "Ab": -4, "Db": -5, "Gb": -6, "Cb": -7,
    }
    return key_map.get(key_signature, 0)


def _escape_xml(text: str) -> str:
    """Escape special XML characters."""
    return (text
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&apos;"))


def _generate_part_notes(notes: list[NoteEvent], tempo: float) -> list[str]:
    """Generate MusicXML note elements for a part."""
    lines: list[str] = []
    
    if not notes:
        return lines
    
    # Sort notes by start time
    sorted_notes = sorted(notes, key=lambda n: n.start)
    
    # Calculate beats per second
    beats_per_second = tempo / 60.0
    ticks_per_beat = 480
    
    current_beat = 0
    
    for note in sorted_notes:
        # Calculate start beat position
        start_beat = note.start * beats_per_second
        duration_beats = note.duration * beats_per_second
        
        # Convert to divisions
        start_divisions = int(round(start_beat * ticks_per_beat))
        duration_divisions = int(round(duration_beats * ticks_per_beat))
        
        # Get pitch information
        step, alter, accidental = _midi_to_step_and_alter(note.note)
        
        # Generate note element
        lines.append('        <note>')
        
        # Pitch element
        lines.append('          <pitch>')
        lines.append(f'            <step>{step}</step>')
        if alter != 0:
            lines.append(f'            <alter>{alter}</alter>')
        lines.append(f'            <octave>{(note.note // 12) - 1}</octave>')
        lines.append('          </pitch>')
        
        # Duration element
        lines.append(f'          <duration>{duration_divisions}</duration>')
        
        # Voice
        lines.append('          <voice>1</voice>')
        
        # Type element
        note_type = _get_note_type(duration_divisions)
        lines.append(f'          <type>{note_type}</type>')
        
        # Accidental (if any)
        if accidental:
            lines.append(f'          <accidental>{accidental}</accidental>')
        
        # Stem
        lines.append('          <stem>up</stem>')
        
        # Staff (default to 1)
        lines.append('          <staff>1</staff>')
        
        # Velocity as dynamic (simplified)
        if note.velocity > 0:
            lines.append(f'          <velocity>{note.velocity}</velocity>')
        
        lines.append('        </note>')
    
    return lines


def _get_note_type(divisions: int) -> str:
    """Determine MusicXML note type from divisions."""
    whole = 1920  # 480 * 4
    
    if divisions >= whole:
        return "whole"
    elif divisions >= whole // 2:
        return "half"
    elif divisions >= whole // 4:
        return "quarter"
    elif divisions >= whole // 8:
        return "eighth"
    elif divisions >= whole // 16:
        return "16th"
    elif divisions >= whole // 32:
        return "32nd"
    else:
        return "64th"


def write_musicxml(
    melody: Iterable[NoteEvent],
    accompaniment: Iterable[NoteEvent],
    analysis: MidiAnalysis,
    output_path: Path,
    title: str = "Untitled",
) -> None:
    """Write MusicXML file from note events."""
    xml_content = generate_musicxml(melody, accompaniment, analysis, title)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(xml_content, encoding="utf-8")